pcall(function()end)
if CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO~=WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO then else end
do WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO=72 end
if _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu~=IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop then else end
do local _={13,69}end
do WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO=WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO or 352 end
repeat until true
do local CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=587 end
if hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd~=hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd then else end
repeat until true
if IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop~=IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop then else end
if _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu then hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=96 end
while false do break end
if CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO~=IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop then else end
while false do break end
repeat until true
if hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd then hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=86 end
if _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu~=IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop then else end
if WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO~=_OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu then else end
do local _=531 end
local ZabcdefghijklmnopqrstuvEFGHIJKLMNOPQRSTUVWCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnYZabcdefghijklmnopqrstuvwxyz_,rstuvwrstuvPQRSTUVWXYZabcdefghijkSTUVWXYZabcdefghijklmn1QRSTUVWXYZabcdefghijklmnFGHIJKLMNOPQRSTUVWXYZabcdefghijtuvwxyz_,OOPQRSTUVWXYZabcdefghijklmnopqoopqrEFGHIJKLMNOPijklmnopqrst0tuvwMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyOVWXYZabcdefghijklmnopqrstuv,EFGHIJKLMklmnopqrstuvIJKHIJKLMNOPQFGHIJKLMNOPQRSTUVWXYZabcST=string,math,table,bit32
local O0UVWXYZabcdefghfghijklmnopqrstuKLABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrEFGHIJKLMNOPQRSTUVWXYZabcdefghCDEFGHIJKLMNOPQRSTUVuvwxyFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstu,_1R1,DEFGHIJKLMNOPQJKLMNOPQRSTUVWXYZabcdefghijklmn,O0deIJKLMNOPQRSTUVWXoBCDEFGHIJKLMNOPQRSTUPQR,DEFGHIJKLMNOPQRSTUVWXYZa_CDEFGHIJDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrsPQRSTUVWXYZaVWXYZabNOPQRSTUVWX
do IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop or 91 end
pcall(function()end)
do _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu=WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO or 95 end
if _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu then IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=59 end
do local CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=918 end
do local _={82,26}end
if WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO then hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=79 end
pcall(function()end)
do CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO or 971 end
local function _0FGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstu(d)
local b='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'
local m,o={},{}for i=1,#b do m[b:sub(i,i)]=i-1 end;m['=']=0
local i=1;while i<=#d do
local a,b,c,e=m[d:sub(i,i)]or 0,m[d:sub(i+1,i+1)]or 0,m[d:sub(i+2,i+2)]or 0,m[d:sub(i+3,i+3)]or 0
local n=a*262144+b*4096+c*64+e
o[#o+1]=ZabcdefghijklmnopqrstuvEFGHIJKLMNOPQRSTUVWCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnYZabcdefghijklmnopqrstuvwxyz_.char(rstuvwrstuvPQRSTUVWXYZabcdefghijkSTUVWXYZabcdefghijklmn1QRSTUVWXYZabcdefghijklmnFGHIJKLMNOPQRSTUVWXYZabcdefghijtuvwxyz_.floor(n/65536)%256)
if d:sub(i+2,i+2)~='='then o[#o+1]=ZabcdefghijklmnopqrstuvEFGHIJKLMNOPQRSTUVWCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnYZabcdefghijklmnopqrstuvwxyz_.char(rstuvwrstuvPQRSTUVWXYZabcdefghijkSTUVWXYZabcdefghijklmn1QRSTUVWXYZabcdefghijklmnFGHIJKLMNOPQRSTUVWXYZabcdefghijtuvwxyz_.floor(n/256)%256)end
if d:sub(i+3,i+3)~='='then o[#o+1]=ZabcdefghijklmnopqrstuvEFGHIJKLMNOPQRSTUVWCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnYZabcdefghijklmnopqrstuvwxyz_.char(n%256)end
i=i+4 end
return OOPQRSTUVWXYZabcdefghijklmnopqoopqrEFGHIJKLMNOPijklmnopqrst0tuvwMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyOVWXYZabcdefghijklmnopqrstuv.concat(o)end
do local hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=620 end
while false do break end
for _=3,3 do end
repeat until true
do WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO=WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO or 87 end
for _=4,4 do end
repeat until true
do local _={67,85}end
do _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu=_OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu or 226 end
do WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO=_OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu or 189 end
local function efghijklmnopqrstuvwxQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_YZabcdefklmnopqrstuvI(d,k)
local o={}for i=1,#d do
o[#o+1]=ZabcdefghijklmnopqrstuvEFGHIJKLMNOPQRSTUVWCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnYZabcdefghijklmnopqrstuvwxyz_.char(EFGHIJKLMklmnopqrstuvIJKHIJKLMNOPQFGHIJKLMNOPQRSTUVWXYZabcST.bxor(d:byte(i),k))end
return OOPQRSTUVWXYZabcdefghijklmnopqoopqrEFGHIJKLMNOPijklmnopqrst0tuvwMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyOVWXYZabcdefghijklmnopqrstuv.concat(o)end
do WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO=IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop or 11 end
if IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop then CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=1 end
do local _={14,30}end
do local _=760 end
do IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO or 1 end
repeat until true
do local CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=56 end
if CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO then IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=44 end
do hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO or 176 end
do local _=884 end
do CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd or 120 end
do IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop or 53 end
local function O00KLMNOPQRSTUVWXYZabcderO(d,s)
local o={}for i=1,#d do
local b=d:byte(i)
o[#o+1]=ZabcdefghijklmnopqrstuvEFGHIJKLMNOPQRSTUVWCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnYZabcdefghijklmnopqrstuvwxyz_.char(EFGHIJKLMklmnopqrstuvIJKHIJKLMNOPQFGHIJKLMNOPQRSTUVWXYZabcST.bor(EFGHIJKLMklmnopqrstuvIJKHIJKLMNOPQFGHIJKLMNOPQRSTUVWXYZabcST.rshift(b,s),EFGHIJKLMklmnopqrstuvIJKHIJKLMNOPQFGHIJKLMNOPQRSTUVWXYZabcST.lshift(b,8-s)%256))end
return OOPQRSTUVWXYZabcdefghijklmnopqoopqrEFGHIJKLMNOPijklmnopqrst0tuvwMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyOVWXYZabcdefghijklmnopqrstuv.concat(o)end
do local hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=257 end
do _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu=IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop or 98 end
while false do break end
do local _=308 end
if CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO~=WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO then else end
pcall(function()end)
if IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop then hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=66 end
repeat until true
if WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO then WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO=42 end
repeat until true
do hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=14 end
local function _lBCDEFGHIJKLMNOPQR_FGHIJKLMNOPQRSTUVWXYZsdefghijk__(d,k)
local o={}for i=1,#d do
o[#o+1]=ZabcdefghijklmnopqrstuvEFGHIJKLMNOPQRSTUVWCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnYZabcdefghijklmnopqrstuvwxyz_.char((d:byte(i)-k)%256)end
return OOPQRSTUVWXYZabcdefghijklmnopqoopqrEFGHIJKLMNOPijklmnopqrst0tuvwMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyOVWXYZabcdefghijklmnopqrstuv.concat(o)end
do IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=13 end
do WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO=_OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu or 60 end
for _=4,3 do end
do local _=916 end
if _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu then WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO=5 end
do local _={25,53}end
do local IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=259 end
do _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu=IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop or 630 end
do CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO or 24 end
for _=3,2 do end
local O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl={}
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[1]='MGIxYWcFMTAGKhQEAzQhFGM0OQgFNjYGAXkHChxmJjYUNzk4OSocHnljJDAbJWI8FihqOgAENghhYDFlA2I8PmEDJGc7eRQwZgRhImZmJDgXNmo6HQcfAgMDYQoLAzRrBGMXHAooMTwWKGMeHSUVBgQHaxoQBDYQEDY2CAVgAmFgYiR9YzYxPDkrCn1mKzkCF3kXfQQoMRwaYzRnAzZiZwAHeQYaBwQCCCsKPhFrNH1gBRcICwBqNBEoORwFABw6AAQcNgpjHB4DKmoWeQNjGBMBBzwaNgplYGYhOHk3FwoTNjlrGyUXPHlrBxQdNz4YBAQKZX0AAmdmfWIGC2cffX0IAjxhKjFnEAEEPmAFMWsKNDkUGDc8NAYoNwZrayYUZwc5EARgBDwDYAca'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[2]='EQgfCBAHCjYXAGM6FSUKZRkGaxgTBxUeYyg+CAhiHzBnNGo4YCg5PHkBNgoTNxo0ZDZhOBcENhAbADEiYQYhAn0AYgYIJSQ6BiU8CGY0Jh47JRcUBioXOgYFNjRjBQd9Gys2AAprJjQEAAI2YCoHNjtiBzwHCyQiEwc2CgM0JCILfT4+eWtrNhprB2tmBDY2EwZrBBAlPAgINwc+AQQCa2EHB2sLKjEcATYkfX0qFzZnKiYwZAE8NAQHBD4ZA2oGFGthPhE2YmVgazw8ZAQ0ZRgDNgRnKzYeOWAxHmA0JAQFNGE0EGI8MBQqFxAUKx9hBjY5MGZnHAIFYiQEAAUCZTt9OTAHKiEiEQNiBhBgMRxjKiE8AgE8ZzkqBxgbZiEIaypiMGMDOTQXKwd9'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[3]='YTRgHgViFzphYmo+AmIKCAdnHDZ5NjwIZis2HmsrMTQCB30IAH05OAZjOTAXNmswFAshNmt5NDALKx8weSsXCAsBNjYQKzYWEGsmCAdrBwQFYhc4FwYkOAcrORwIJQoICioXHB0EYzQXBmIcCggcOAVifQhrYhQEBH0xOgI3MQJkNCFhCjQnBgQACgoFA2oiBAAKOAAqCmUaBmFrYH02OBh9NDw5YhccFGs3Bn0GJx4XBAIiGAUCZXlrBxAcYwoKC2MmAhwoNAgRKjlhHGIhawEBFz45KjkGGCUXNDsqFD55NzwwBQccBmdjHwIYYzFhCjYhPBZiHDxjNGM0AGM8axgBCmUVeQIiHX08CGBgHwgRNH02EysfFHlrMSIWBzkKYAQ+ABgHBxYRADEw'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[4]='FQE5MBpiJjwRCB8AEWMCaxkHHx5kAwc4CARiBhYoYjAQKwc+Gn0xNAoDHDoZAQIIZAccGgpjFxxnNmoGeQQXAhcDPCIdayYIeSprCjsrGgQYNjkeAQEfEH0rHDwIJWIUFnk0ZQQ0ITZ5NDFhCDcxHBoFB30BBzFlYwNiOhEGIQQYNCR9BAB9PgUGJAgRNj4WFWAxFBxiBxQXA31nCgM5AgAAJCIXNmE4CisHNANjFxQINmsWCAMcCgoLJCIFJTkKBQQ0PhkHBzoLAQIwBioUChclF30RKD8eAwQHEBQAMWcZAH0KEQdqYRo3HApmJSY8GwQmBhc0MTpkNiE+HQc2EGcoan0XKDwKGQc0OmBiHzAAYmsQYTQ/HnlrJjAIawcefWIxZQoHCjZjAwQA'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[5]='BDQxHBY2ahpkNmM6Zwd9a30ANx4IBBcWOyVjPgcDPDRrYx8CAioxOn1jYTADZiYCCAd9IgoFFzhmNx0eE2IKOAclYxYIB2JlOWJiMBUofWcFKxcwFWsxHGMqMQYKA2owFmsHAnkAYwAaYgccHGIHMGdiHDhgAyEIZAYmGhsAPCIQNGJ9AwAxABooaiJrKGoWCAM5PmF9eR4BJTQwG2sxEDslFQYEBGocFmI+MAhnAjgAB2FrfWs2NAY0PDBnAQcWGypqaxMrHxxnY2MAZ2tjAGE3B2UHJTEWOX1qBGADYSIEeT46eSsxHBU2YmUXNCE2FX1iNAE2amEKACYeFDY5HAg3FxAceTQ4GGIUAgJjNwYGA2JlBAE8fRUBOQBrJQQKFSoHBGF5BAZhYwQE'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[6]='ASohPBgEFxoKBGMCZAchPAADAjwVKxwCa2thPAclGjA5YyY0A2IhAhABHwhhZiEGAwQhZ30FNh4QYjRrGCUxBGQ2JjQbBH0KOWIxHmEFFxo5Kwc6ACsXfQh5F2EHY2sEG2IxChEAORAQACE2fQEaa2cAAjRgYx0GCiofawRiOQAGKwo0YAsmGgZrYmdmBB8UBTY+PjkqFzAKBmMQYwRjNhcHBzBjAQJhEwQ+GgUqOQAABQciZyUfGmQGamUTawcWBmIkawAqAjRjYwo2Znk5CB0EBwoGBDFrYyVqfQQEFxgdeRcEEWA3HggBPhxnATEEFWtqNDkqFxRnBRpnACo0fRF5PAgGKH0EGCghPAIqax55KxQ4YWs0OhgEahgFYn06AQdjHBV5AmUQKzw4'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[7]='O31hIhsFGiIHNiYQCGIfGgAqBQYYBRUefWtiFhc0NDwHNzx9YHkUPmZjGmsGNz48CmtqNBcHajgDfWJ9aypiEBUHPDQcJTEEAShrAAAoJgQEKhwEeQRiBARrCjgYKiY+YH05BgA2MRxgeRQcHQACZR0oeR4GJRwYCzY+PBtgHz4dKwpnGCohZRgrHAoBATkKGyhiEAZiAjYaKCYcHWI2EBEqAmEDJWJnFAccPgVrMSIIJWIIZgshPGMDPjwCAQoKGwcfNhtgBDBjfWM+FgA8NjtjYQQQYDE2OyhqAgclfTYKa2o0ZgQfPgNiYwQRA302CjYkNBsHNGtmADwIAyViGGZrYjoWBR8KFARrFhEHfQoTYDEaY2IXNGQBFxQWBDEEFQAmEBp9IQI7fTYA'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[8]='CyomEAc0PCIFYj4UYQRrOmcHPDgGYwI4EysXHAQHCjYZAx8+ZjR9ZxYHIQQGJSEQGDYmHhhrOTpkNjkcF2AaYQUlazwaNGEwYQZrNBdjHwAGJSY6B2sEEGElfTQGYzkifQEHPh1iYT5nAz4YAQYxOARjNAQFfWphETQ+NhcDagIaBjceYXk+HmNnAjRgBRcCHGMhEHljPGVnKjlnAyofOmYHBzgENDkEBwQ+BAEqORZhfWFhBAQ5YREEPj5nKGM+ZDZjCAArHBgXBD8GZyUmHBs0MTAVBjwwBWs0NBkIHxYLBAc4ZiUkOhp9MRRgfX0+ZgQHMBYlIQIDKD4cFTRiBhE3PjZkBRciO2AEAhhrahAHAx8CESoxMAYLJjQEAzE6HQAxOBEHFDoFBzE0'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[9]='Y2A2OBcqYWsFAwccZyViGAEBHDRrYAJ9YARgBgAAPh4XKgUGAQNhCBMHMT4DKjE0FQM2FGAEIQoEKjQ6HQEXFhs3BxwKfWsCEDYKaxZiYzYHNiYUBGAxCB0DYQoIfT4UG2tjGBZrOQYHA2I+HWMKZxNiJggXKhcGFGI+MB0qMRAVBxoKAwBrBBF5F2cWfTkUCGMfIgE0Yxg5YmprfQA2HBMBNgpjKmprAAQ2BBQrHwAGYDQIASgmPgs2amdhNCEiYAc2Ogd5PGcEACE+ZgN9YQc0fQoAYiQ0CgBqGggEAjwDNDkcZwchAAsDORQTYjw0GTRrPgFjMTxhYyYaeQMHNAEHFDoGNxQIECoEChclAjA5KwIKBgZjBBs0fToEfTwwEGI5ZxZiFz59NxQw'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[10]='ACU5Pn03BAIVNxQCFGIENgAEF2ULBRwKGTQhOGYFNH0XayYIYwc+EAgANhwXNGs+GgYmMAEHHwZnKmI0HSsfOAN5NwZ9KGsweQRqOBolajYKB31lE2IhNBgDYwIYJSRhOWtrFh00YWULKiYYAAMEAgI3BAIWKgI+BGJqa2crOQYVeQQ+GGthNAZgFzYCY2FlGgRrFn1rYzgcKxc0ZgUXCAgDPDYQBGs+Zys0CgsqNhwXYzw6ECUaZRZiHx5neTYKayhqGgR5NgR5fX06HWNjCmQAYhAEKho4CAcfPhYHPGEKBiY2AQdrNAsoJjoaYB0GATc5HAR9NGsHBGoYEwc0ChUBPh4RazkKGzQhBmEDAgoKA2IaZgYkfRkDHx4LYwI8ESsXawgAazx5YmM0'
for _=2,3 do end
while false do break end
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[11]='G2AfNgpjBDAHJTRlBSofNghiBDxjYwciAARhOGcAamsBJRQaGnk2Ohd9PGtrJRQ6AAc0PhAEHzpmACEKfQY5ChQ3OQoYNzw0AH0+MANiamV5ACYcC2AUCjkrBAQCa2oUAGA2ABoBNjZmayY4GwY5NhA3NhAKAAp9GGshFBAEfT4INjEGEyVjCh15B2dja2oeAXkEOBg2YWcbYDFrF2MUMBoEYzgGYwIKEyofAB0HYgRjBTY+ZAY5OgcFGjAQCyQEEyoUAmtiPhwBeRQECANiPH0GMTQEazYCBQQkBBYGNAhrYxQICwEENgo3HDYcKiQwGDYkNBViJjwXBCFlCAMUNAMlIRo7KDYUAigmHh0rBz5hKD4IFAAHfQMBAjQHAGsYAyU5awooIRQZAyEI'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[12]='FSV9NAB5NgAKYDceATYEOmAqYn1rYgI+YGMcBnlrYX1ra2M8AjZ9CBQqPjRgNx8cFwQ5CgQFBwQKAH1hAWcfHBxrPhYBBx8KBSoxCAsBNDoAYBQAFms+FBADHAJhByRlADcXAhoEYhwGBzQwGmJgBhdiazA5eQc8A2M5ZQs2YTQ7YmE+Cms5IgoDagYUeRcUA2I+NBVjYhwKBGIefSoaYQhgCgQECB8CAAUdHhR5MQYUKn1lZAsmChUBAgQAYjw2AwNqIhgBBz4BBwdhY30mGgsoIQIbBRw2YXkENH1mJCJjKwQaBAcfBBRrNgpjNxQ2BgYmCmNgGn0ZA2IaG3k0MAsrMTwEBD8eFn0mADklahhnKgo6A2MEMAIqYzQdNwo4GmIfBAIoOR4IYjwI'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[13]='OWIcPAFjFDwANwQ0AnkXIgdjYgIGYwprYzcKIjt5FAgUBxcYAgYmMAo3OQQANiEaGCUkChg3PgIKfSFnBCU5FmclFwoXAD42ayUhGmA2azgRKiQ0OXk5GjkqYhQaKzE+ZAdrPhF5Gj4XADwiAmIfEDljBzZhAwcIHQQxCgI3PgAAa2s0FQMEEAI0OTAYNxceCwAhChZgAjhhfWo0EwcfMBQACmcTYh8KeWI5AjkqYhYKKz4GFGAfEBAlMRwHAwIIGn00ChNnHwQZNx8AFQBiNGMoYAYXJSEGAQAfCggBByJmeRw0CANiBBcAF2VrfWIICwUfHgYBORwFATx9BjQmBGtjJCITAwdhfSpqNgMBMRwGA2IAHQdjCAI0IRoHKzEiBAQXIhYFFxgZBmI8'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[14]='O2IVHmYoazZjYgJnBggcPHkFFDwKYAI2BmM+CgIAYzp5eQQGBwMkCGd9YwICYx9nGiVifWQAFzg5JQp9E2I5YQZ9NDoKKCY+BAMkNBZ5Fx5rayEaYSokChsqMTYIYmI0AGMcPAAAH2UbKiYYfWIdBhYGYX0EAwoiBAQkZwUqYhgcKDk+ZgR9NhQAeQYBa2o6GgQ8OhQBMThmYjkGHShrNmQEYgQYBRQ+F2IfHAooPGsbAzY+ZDZjAAFjJhQRNxQcCwQCZQIqfQh9eTEUHWIUBhdgHxZ9YwoEGQE0BANiCjoHeR0eY2ACPgc0Px5jeTYKCAMaa30AOTAANGI0YCoaa2YrB2sCfSY2CwUUCAoGYwoDKh8YCDYhZx0qNhQKNGo8YGccNhYrBx4HBB9n'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[15]='ECVqNBUFMTAdYmo8GwY5GgYBHAIKNwc0HCsfEB03HBoXYwJrGwBqEBEHBAYRKzkYCgUXYWslBxQDJSQ0FShjOgJjIRAaBRQ4Zn1iFmdgHwYCKgQIZAAFHgEEHBoZBAQ4BABjABoIHBwLeTceFGAUNhAHeR4RAD4+YCgkOmd9fQRkNmEiGgUHBBU0aggHKgI4FwcxGhQ0MX1jKho4GCo5AhADHBgEBAcWCDc5FBUECmEYZiRhZisfGgYGIRoaeRwAFQACZxAIHwoBNjQiFwcXazsqajpmNjxleTZrGAglPGsbKzYwCAE8fWEDahwHKjECfQRiNGdnHQYaARciayVjABUHORoFBQo2ZzY+GgIoJhQGKzk2BCg8IhELJwYQAD8GFgA+NgtiPAgYYgQ8'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[16]='FgBiEAQrHx4QB2I4ZAMHPDsrPAQYCB8IHQQhFgUDORoXKDE8AWIkChZjBAJmKzkaHCUEPjslGjodYxcKGAMHFGBjYgpjAQUGFAEKMGQAYTYYfWsAOyh9OgoHPhAYYj8eZ2NiAAU3NgpjNmEEGQQXFgJ9Ph4FBn02FGcfEAUoJhgcfWFhHSghCBsrFBAGKms2GANqfQQqax55JWJ9YGIhfWQAHDRgNjRlYAZrBhYGamcZCyE6GnkXOBYrHAYFYhwQZgdjNjklFBwXNmMGeSV9ImtrJgR5eQc+YQchGGA3GmUGBR86YQQCfRolJgoEADFnEAE2CgcAOQgKNDE2FwYhChEqNjYIBiR9FCUhCmEAJGVgJWp9HTc8BBsDfQh9Nx8eAgAKNgErBzwGKGIY'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[17]='a2I0NhRrYmU7fWoUBys5PgoGazx9BDEWHSs0OhgqFBwLKiY2EGYkOhcLIQQDJTxrFCU2CAcHIToYKiQ2A2IkNgElPAg5JRo8E2YhBGclOQAIKGM6B2AxBgIlFzgZBzEQZwQENhxjazYYJTk6CypjCAJraxwKawQwZ2s8a2djYWECKzxrCihrBGEoMTprfWo4a2MmFAdgNhgcayFhB2YhEDslPGcLKgUeZwQ2HBUrMRgQeRQCZzQhIgsrBAIYBDEKATZjAgorBzxgND4AHQAKCH0lHwgXfTkAAig0IhE0YX15azRrYSUCNn0BGmthBR8GZwskCAZ9YxoXYxcEYSgkCgcGYmEDKzEcfQYkZxcHPD4ENjQwAmACNAc3HxAaNiQiYShrNBQ0YToYABo+'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[18]='HWI2HhNgHxwYAx8UZgdjFnk2Nh4cfSYaEXkfEBQHGjQLBD44EAE0IgADF2FrYB8afSU0ZxcGOWcBATkIFQMhMAolMR4BfTFlCCoxEBQ2YgphfTY8GCpiMBcrPD55ZwJrFQQ5NmYqajwTB2p9CiUCYQR9axwEBiYKEyUkCAFgNDgIARwKGQUcBh19JjwKY2E6YAAfBAUlJghjKwplFwQkCAAHGmVgBzlrAQEEChd5Ngh9NDEUBAAmAjsoYxhmNwcACAY0MBYlYWcWYDY+YTY0IhE0ITgbYBcieWsHZxtjNAoVKmoKFAU2CGcHJGdmNz8eEAdiNmE2YjgWBDcGFQQ+BB1rOWFhayEeHSUHIjsrBzYIBz4CAWM8OmAoMR4FAzkGCAMKOGdiazQQKCE2'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[19]='FgUKNhhrBxQEBBcGEQECNgQ2amEXNzYcYCgxFmFjITw5KiQEBWskMBsABxYUNmM6a2NjNmBgBzQDATY8YWthOhc0MRwaNzRrFQNrAGtjCmsXJWprAnk0axYDOR4IA2oYC2AxYWcDHDQdAB8KAiU8fQsoYmEAARpnGgcmPBABHAYKfTw2ACUEMBY2YjgXBxcUOWcfNgdrCjYHAwUGCgQ+NAAGNgYKKxoiAwEHEAQqIToIACYGFmIfGGElBDATNx8ECwUaMBMANCJ9ZiY2EHkXCGYHND4ZNzllYGImGnkGPARgJTk2OXk5EHkFMTwBeTllGgQfCnklIQgEJTQ2Bn1qGgU3HxQRBGF9HQQcAHkoJDxjACYcO2MfPmEqNjYbBwQQFAYkNghjYzhgBiQ4'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[20]='YX0xEGMDPGdhBTQ0BAA5BgM3OX0ZBBo0AAcUPhgHBxgXJT4QFSohawhjFBhjAzYcGQMVBmEFFDZ5Nx86HCpjPgMGYzgaeTQ6ESUhCBQGIT4DKmMwAiUHa2M2JgJ9Y2oEfTcxGBQDBzQUBCEAGgUENBg0Ygp5ADY2AmMXNhFiJjxnKwQ0FQNiYTtiGjoLAAQ0OXkVBgUEAjwRB2AeHQMCCgMEMRAKYzQEEyoXGggqJgoGeTFnEAAkYQp5HzQRYBc0BWIaCB03PhhnNmsAFQcfFAILJhwXBGoCOSg2NBhrahAHBjxhCgMfHAIABAIaBmoAAzcEGgUrPhQCA2s0GQYxFBBiMWsWAB8CYQcXIhpjBDQYATkUHGNrGAUrMR4BAQIEEwQ2FgAFHxBrKj40'
do hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO or 57 end
do hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd or 38 end
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[21]='ECoUHBpiagJgBzQ+C3kEPAgqBDALNGIIeQE8ZWElYgIBBmIAeQAcABAlPDQTJWoUEGtifRh5HR5mAGM8AyscMABnHDQYARwUCiUffTljOTo7fSEaFABjPmFiH2sLA30iAisCawY0ORA7eQd9Gyg2FmBraiJkBGE2EAEUFBY3FzgGBzQIAgUKOBooMTg7YzkGFWMHAmBiBxwaJRcWEGsxPgdiYh4EAzkcF2JrHhRraxgafTkQGTRhZRRjfWcHCB8UGwAmHGZ5PDZjfSYKFQQcCGElYmcGJRwAYH05NmQHIQQTKn0iBjQmAAc0axYEeQdlFSodBgZrCn0HBBo4GAQfPGFifQoaKwIKCgU2PH0AFzgZAAIKZmMUFBRjBxA5fWI8CjYhGGcAFxAANH0i'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[22]='GgAkPBMqFwobKxQQYX05ZRMEBDoBKxo4AAE8PDkqYxQUBxw8EDQ2PgMqfT4WBDYUBjc5Zxs3AjAafX0EHGJqEBAlHxAZAGJlHWACYQR5NjwAADEeY2cCOAsEOToRBCRlFwEHImQ0YwgLAxo8AAY+FAN9YTQGeTY0E2s0ZRslHDgaKjlhEQcdBmYBMRodZiFhCDQkawRjJgAVNwowO2I+GmQHBxg7YB8eGgMCOgg2fWsYBBwUCCUhHn15BwQ7KzkaG2IxGBAAfWcFACF9eWNiNgglNwZ5KmJ9BmIfFDl5PGsVKDQ2CgY5MBkHPARgAGsYa3kxIhcoNggEawoKOSs0ZX19OT5kCyEaYzZgHmM0YhQFByFhAyg8NgQDHzQTCyFrOWsKPDkoIWsbB2oe'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[23]='HTZiPmcrMRx5fTk8ESg0OgMEHBwFND42OyUEMB0AajhnY300fWccOgZgFBhhY2s0FDY8OgR9ORQCKiQ+a2AfPDtrYAZhNDQKOyVjFAAHGj5gZiQIGjZjOhR9amFmeR88fWAcNBR9awAIayEiBDcCaxpiaxQTNiQEAABqMGcAMRAUYDFlfXkFHgAoYSJnYjYQFyhhPBkAHwAKBxQGYzQ+MAUlNhAUKhQGBjYHGnkBHBhgYz4cCCh9CANiHzpnayYWCnk5MGQDBxY7Y2IGFjY8CBoBMTgHJTEcGwYhNBRiIRYWNxc0GAEEOARjMRQHBDY4YyU8fQN9MQBga2o4OSsKIgprYmECBzE0BWIaIgIqNjgTfSECHSoXMBcBPgAYJRQGAjQhGhYDfQgFJSEY'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[24]='HCsxFhVrIQIIYBc+EAQ8axwlYwZrYAQeBDZjFmFiJD5gfWo4CiphZxpiFAADAQJlGAQ0IgBrOTw7JTkACnkxYRAFNDwBNgcIFCUkfTt9fWULNiEaY2MfaxUDPjQKAx86YGNrFHk3BxYcYAo8fSgkChsqH2sCJT4EYAshEBRjHAAVNmsaFWJiMHkLITwRa2o6Zio5PhAGYmVjNiEKOyhiYRZiYzphByE8EQEXPn0qPH0dBwcwYTQhCBADNGUXAAcWBQQaYQQoIQobfSYWESghEAZ5FzoUNmswFwA+PBMrFwgFKmoEGwUHZwA2YxwUBx84AmMhCAoGIQYFB2IceTZ9MAgqFzYaKGs8HSUmABk0IRY5fSYKOWsFHgNjPDAFBmIWFWsxABhjJGcCNCQ+'
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl[25]='HWYkChpjJhhkBiQ4CzcfGGsrF2cHNwQ2eQUxNGQGJDQbADYkMCVvbw=='
O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl=OOPQRSTUVWXYZabcdefghijklmnopqoopqrEFGHIJKLMNOPijklmnopqrst0tuvwMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyOVWXYZabcdefghijklmnopqrstuv.concat(O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl)
do local _={9,17}end
if IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop~=CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO then else end
do local _={98,23}end
for _=1,1 do end
do CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=_OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu or 7 end
for _=3,1 do end
do local _=479 end
repeat until true
do hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO or 860 end
if IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop then CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=73 end
local _lWXYZabcdeYZabcvwxyz_BCDEFGHIJKLMNOPQRO={174,1,193,44,125,82}
if WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO~=hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd then else end
while false do break end
if WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO~=WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO then else end
do hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO or 51 end
if _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu then IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=49 end
do CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop or 40 end
repeat until true
do local _=915 end
do CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=61 end
local function BCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqjklmnopqrstuvwxyoEFGHIJKLMNOPQRSTUVWXYZabcdefghijhijklmnopqrstuvwHIJKLMNOPQRSTUVWXYZabcdefghijCDEFGHIJKLMNOPQRSTUVBCDEFGHIJKLMNOPQRSTUVWXYZabcRSTUVWXYZabcdefghijkl()
local d=O0STUVWXYZabcdefghijklmnopqrstuvwxyzYZabcdefghijuvwxy_mnopqYZabcdefghijkl
d=_0FGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstu(d)
if not d or #d==0 then error('L8')end
do hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO or 10 end
do local _=430 end
do IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd or 866 end
do local _=596 end
d=efghijklmnopqrstuvwxQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_YZabcdefklmnopqrstuvI(d,_lWXYZabcdeYZabcvwxyz_BCDEFGHIJKLMNOPQRO[6])
do local _=432 end
do local hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=388 end
do IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=_OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu or 38 end
repeat until true
d=_0FGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstu(d)
if not d or #d==0 then error('L6')end
do local _={77,88}end
if CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO~=hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd then else end
do _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu=CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO or 291 end
do CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=_OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu or 90 end
d=efghijklmnopqrstuvwxQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_YZabcdefklmnopqrstuvI(d,_lWXYZabcdeYZabcvwxyz_BCDEFGHIJKLMNOPQRO[5])
repeat until true
pcall(function()end)
do IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=_OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu or 23 end
do local CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=681 end
d=_lBCDEFGHIJKLMNOPQR_FGHIJKLMNOPQRSTUVWXYZsdefghijk__(d,_lWXYZabcdeYZabcvwxyz_BCDEFGHIJKLMNOPQRO[4])
do IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=97 end
do IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=22 end
for _=3,1 do end
if CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO then hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=80 end
if hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd then _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu=96 end
d=efghijklmnopqrstuvwxQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_YZabcdefklmnopqrstuvI(d,_lWXYZabcdeYZabcvwxyz_BCDEFGHIJKLMNOPQRO[3])
do hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd=hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd or 56 end
do CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=55 end
do _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu=97 end
if CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO~=WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO then else end
for _=3,1 do end
d=O00KLMNOPQRSTUVWXYZabcderO(d,_lWXYZabcdeYZabcvwxyz_BCDEFGHIJKLMNOPQRO[2])
do local _=70 end
do local _=655 end
do local _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu=418 end
do CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=71 end
d=efghijklmnopqrstuvwxQRSTUVWXYZabcdefghijklmnopqrstuvwxyz_YZabcdefklmnopqrstuvI(d,_lWXYZabcdeYZabcvwxyz_BCDEFGHIJKLMNOPQRO[1])
return d end
do local _={57,27}end
do _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu=CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO or 375 end
do local _={46,37}end
do local _={23,46}end
do WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO=35 end
repeat until true
pcall(function()end)
ZabcdefghijklmnopqrstuvwxqrstuvwxlmnopqropqrstufghijklmnopqrEFGHIJKLMNOPQRSTUVW,JKLMNOPQRSTUVWXYZabFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopq_DEF=pcall(BCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqjklmnopqrstuvwxyoEFGHIJKLMNOPQRSTUVWXYZabcdefghijhijklmnopqrstuvwHIJKLMNOPQRSTUVWXYZabcdefghijCDEFGHIJKLMNOPQRSTUVBCDEFGHIJKLMNOPQRSTUVWXYZabcRSTUVWXYZabcdefghijkl)
if not ZabcdefghijklmnopqrstuvwxqrstuvwxlmnopqropqrstufghijklmnopqrEFGHIJKLMNOPQRSTUVW then error('Decrypt failed: '..tostring(JKLMNOPQRSTUVWXYZabFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopq_DEF))end
repeat until true
if _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu then WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO=46 end
do CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO or 61 end
pcall(function()end)
if WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO then WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO=84 end
for _=2,1 do end
EFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop0PQRSTUVWXMNOPQRSTUVWXYZabc,_O1nopqrstuvwxyzLMNOPQRSTUVWXYZabcde=load(JKLMNOPQRSTUVWXYZabFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopq_DEF)
if not EFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop0PQRSTUVWXMNOPQRSTUVWXYZabc then error('Load failed: '..tostring(_O1nopqrstuvwxyzLMNOPQRSTUVWXYZabcde))end
pcall(function()end)
do local _=238 end
while false do break end
if hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd then IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=39 end
do local _=961 end
do IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=73 end
pcall(function()end)
IlHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqJKLMNOPQRSTUVWX,IJKLMNOPQRSTUVWXYZabcdefghijklmnopqrsSTUVWXYZabcdefghijklmnopqrstuvwIOABCDEFGHIJKLMNOPQRSTUVWNOPQREFGHIJKLMNOPQRSTUVWXYZabcdo=pcall(EFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop0PQRSTUVWXMNOPQRSTUVWXYZabc)
if not IlHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqJKLMNOPQRSTUVWX then error('Exec failed: '..tostring(IJKLMNOPQRSTUVWXYZabcdefghijklmnopqrsSTUVWXYZabcdefghijklmnopqrstuvwIOABCDEFGHIJKLMNOPQRSTUVWNOPQREFGHIJKLMNOPQRSTUVWXYZabcdo))end
if hijklmnopqrbcdefghijklmnopqrstuvwxyz_VWXYZabcd then WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO=53 end
while false do break end
do local WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO=215 end
do WXYZaboNOPQRSTUVWXYZabHIJKLMNOPQRSTUVWXYO=CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO or 63 end
repeat until true
do IJKLMNOPQRSTUVWnLMNOPQRSTUVWXYZabcdefghijklmnopqrBCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnop=79 end
do _OPQRSTUVWXYZabcdefgbcdefghijklmnopqrstuvwxyzHIJKLMNOPQlQRSTUVWXYZabcdefghijklmnopqrstu=34 end
pcall(function()end)
repeat until true
pcall(function()end)
do local _={12,19}end
for _=3,1 do end
do CDEFGHIJKLMNOPQRSTUVWXYZabcdefgXYZabcdefghijKLMNOPQRSTUVWXYZabcdghijklmnoO=62 end